### ISSUE TITLE
switch to a demo script rather than ipynb

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/vsvf-monai#4]
After thinking about it more, I realize that it's much harder to collaborate on a script because ipython notebooks just don't work that well with version control. Constantly remembering to clear output cells and using an external tool like reviewnb is not necessary. Let's stick to making a demo script. When we're done, I can write a tutorial-style notebook based on the script.

**Comment by sonic1sonic** [comment]
Totally agree that ipython notebooks don't work well with version controls. For the demo script I think we probably should work on designing the I/O (i.e, function/class signature and return value) and architecture before start off actual coding.

**Comment by ebrahimebrahim** [comment]
@sonic1sonic Glad you agree! In order to approve the PR #5 you need to be a collaborator on the repository, so you have to accept the invite.
