### ISSUE TITLE
Create synthetic data generator

### ISSUE THREAD

**Issue by ebrahimebrahim** [ebrahimebrahim/vsvf-monai#6]
I propose we make a little synthetic data generator to start with. Once things are working with synthetic data, we can work with a real dataset.

One of #6 or #7 needs to be done; whichever is done first makes the other a lower priority

**Comment by sonic1sonic** [comment]
Sounds great! An alternative solution to the dataset preparation is that I can pull something from the existing OAI dataset and I can also export the momentum and warping field generated by our trained network for us to verify our implementation in the future.

**Comment by ebrahimebrahim** [comment]
That also sounds good! We can do both; whichever is done first will let us move forward. I will open an issue and assign to you
